<?php

/**
 * E-Store API - Digital Commerce Platform
 * PHP version 8.1
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Comprehensive REST API for e-commerce operations including: - Product catalog management - Order processing and fulfillment - Customer relationship management - Inventory tracking - Sales analytics - Review and rating system  Supports OAuth2 authentication for secure operations. Version: Production Release 1.0
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@estore.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace OpenAPIServer\Model;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Model\Address;

/**
 * AddressTest Class Doc Comment
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Model\Address
 */
class AddressTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Address"
     */
    public function testAddress()
    {
        $testAddress = new Address();
        $namespacedClassname = Address::getModelsNamespace() . '\\Address';
        $this->assertSame('\\' . Address::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        self::markTestIncomplete(
            'Test of "Address" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {
        self::markTestIncomplete(
            'Test of "street" property in "Address" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
        self::markTestIncomplete(
            'Test of "city" property in "Address" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
        self::markTestIncomplete(
            'Test of "state" property in "Address" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "postalCode"
     */
    public function testPropertyPostalCode()
    {
        self::markTestIncomplete(
            'Test of "postalCode" property in "Address" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
        self::markTestIncomplete(
            'Test of "country" property in "Address" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = Address::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}

