<?php

/**
 * E-Store API - Digital Commerce Platform
 * PHP version 8.1
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Comprehensive REST API for e-commerce operations including: - Product catalog management - Order processing and fulfillment - Customer relationship management - Inventory tracking - Sales analytics - Review and rating system  Supports OAuth2 authentication for secure operations. Version: Production Release 1.0
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@estore.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace OpenAPIServer\Model;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Model\Invoice;

/**
 * InvoiceTest Class Doc Comment
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Model\Invoice
 */
class InvoiceTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Invoice"
     */
    public function testInvoice()
    {
        $testInvoice = new Invoice();
        $namespacedClassname = Invoice::getModelsNamespace() . '\\Invoice';
        $this->assertSame('\\' . Invoice::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        self::markTestIncomplete(
            'Test of "Invoice" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        self::markTestIncomplete(
            'Test of "id" property in "Invoice" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "orderId"
     */
    public function testPropertyOrderId()
    {
        self::markTestIncomplete(
            'Test of "orderId" property in "Invoice" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
        self::markTestIncomplete(
            'Test of "amount" property in "Invoice" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "tax"
     */
    public function testPropertyTax()
    {
        self::markTestIncomplete(
            'Test of "tax" property in "Invoice" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "issuedAt"
     */
    public function testPropertyIssuedAt()
    {
        self::markTestIncomplete(
            'Test of "issuedAt" property in "Invoice" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "dueAt"
     */
    public function testPropertyDueAt()
    {
        self::markTestIncomplete(
            'Test of "dueAt" property in "Invoice" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        self::markTestIncomplete(
            'Test of "status" property in "Invoice" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = Invoice::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}

