<?php

/**
 * E-Store API - Digital Commerce Platform
 * PHP version 8.1
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Comprehensive REST API for e-commerce operations including: - Product catalog management - Order processing and fulfillment - Customer relationship management - Inventory tracking - Sales analytics - Review and rating system  Supports OAuth2 authentication for secure operations. Version: Production Release 1.0
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@estore.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace OpenAPIServer\Model;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Model\OrderCreate;

/**
 * OrderCreateTest Class Doc Comment
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Model\OrderCreate
 */
class OrderCreateTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "OrderCreate"
     */
    public function testOrderCreate()
    {
        $testOrderCreate = new OrderCreate();
        $namespacedClassname = OrderCreate::getModelsNamespace() . '\\OrderCreate';
        $this->assertSame('\\' . OrderCreate::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        self::markTestIncomplete(
            'Test of "OrderCreate" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "customerId"
     */
    public function testPropertyCustomerId()
    {
        self::markTestIncomplete(
            'Test of "customerId" property in "OrderCreate" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "items"
     */
    public function testPropertyItems()
    {
        self::markTestIncomplete(
            'Test of "items" property in "OrderCreate" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "shippingAddress"
     */
    public function testPropertyShippingAddress()
    {
        self::markTestIncomplete(
            'Test of "shippingAddress" property in "OrderCreate" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "billingAddress"
     */
    public function testPropertyBillingAddress()
    {
        self::markTestIncomplete(
            'Test of "billingAddress" property in "OrderCreate" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "paymentMethodId"
     */
    public function testPropertyPaymentMethodId()
    {
        self::markTestIncomplete(
            'Test of "paymentMethodId" property in "OrderCreate" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = OrderCreate::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}

