<?php

/**
 * E-Store API - Digital Commerce Platform
 * PHP version 8.1
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Comprehensive REST API for e-commerce operations including: - Product catalog management - Order processing and fulfillment - Customer relationship management - Inventory tracking - Sales analytics - Review and rating system  Supports OAuth2 authentication for secure operations. Version: Production Release 1.0
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@estore.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace OpenAPIServer\Model;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Model\ProductCreate;

/**
 * ProductCreateTest Class Doc Comment
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Model\ProductCreate
 */
class ProductCreateTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ProductCreate"
     */
    public function testProductCreate()
    {
        $testProductCreate = new ProductCreate();
        $namespacedClassname = ProductCreate::getModelsNamespace() . '\\ProductCreate';
        $this->assertSame('\\' . ProductCreate::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        self::markTestIncomplete(
            'Test of "ProductCreate" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        self::markTestIncomplete(
            'Test of "name" property in "ProductCreate" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
        self::markTestIncomplete(
            'Test of "description" property in "ProductCreate" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {
        self::markTestIncomplete(
            'Test of "sku" property in "ProductCreate" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
        self::markTestIncomplete(
            'Test of "price" property in "ProductCreate" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "initialStock"
     */
    public function testPropertyInitialStock()
    {
        self::markTestIncomplete(
            'Test of "initialStock" property in "ProductCreate" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "categoryIds"
     */
    public function testPropertyCategoryIds()
    {
        self::markTestIncomplete(
            'Test of "categoryIds" property in "ProductCreate" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "attributes"
     */
    public function testPropertyAttributes()
    {
        self::markTestIncomplete(
            'Test of "attributes" property in "ProductCreate" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = ProductCreate::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}

